export default {
  login: 'login',
  signUp: 'signUp',
  signUpConfirm: 'signUpConfirm',
  oauthConnect: 'oauthConnect',
  signUpSetUp: 'signUpSetUp',
  generalError: 'generalError',
  forgotPassword: 'forgotPassword',
  requestSignUpRegistration: 'requestSignUpRegistration',
  resetPassword: 'resetPassword',
  updatePassword: 'updatePassword',
  validatePassword: 'validatePassword',
  sendConfirmationEmail: 'sendConfirmationEmail',
  createUpdateExpense: 'createUpdateExpense',
  expenseList: 'expenseList',
  insightsMonthly: 'insights',
  insights: 'insights',
  categoryList: 'categoryList',
  goalList: 'goalList',
  oauthIntegrations: 'oauthIntegrations',
  createUpdateCategory: 'createUpdateCategory',
  updateProfile: 'updateProfile',
  paymentProfile: 'paymentProfile',
  cancelAccount: 'cancelAccount',
  preferences: 'preferences',
  import: 'import',
};
